### ISSUE TITLE
Backend Race Condition

### ISSUE THREAD

**Issue by jdevries3133** [jdevries3133/song_maker_gallery#24]
A race condition happens on the backend. If the user spams refresh while the gallery is loading and the backend is also going through `fetch_and_cache`, multiple calls to `render` are made, and so the fetching and caching process is happening over and over again:

https://github.com/jdevries3133/song_maker_gallery/blob/19b7d99b651e58f2a43a2401951ec3d16374fd4e/django_smg/gallery/services.py#L31-L34

I thought that the caller was selecting the queryset `for_update`, but it appears that actually isn't the case. I wonder if fixing this will fix the race condition?

https://github.com/jdevries3133/song_maker_gallery/blob/19b7d99b651e58f2a43a2401951ec3d16374fd4e/django_smg/gallery/serializers.py#L117-L119

**Comment by jdevries3133** [comment]
I realized this is a bit [tricker than I thought](https://stackoverflow.com/questions/46945790/why-could-select-for-update-simply-be-ignored-with-databases-that-dont-support)

I'm not really sure that I'm equipped to test for this, but after throwing a select_for_update() in there, all the tests still pass. Whether it will improve production performance, I'm not sure, but I think it's the right move to have it in there anyway and maybe that saves the race condition.

**Comment by jdevries3133** [comment]
Commit 8ddf3f9dc13c539cee9fbe5e3ceb219758a8841f did not fix the problem and, in fact, caused rendering of new galleries to fail. This feature needs to be developed and tested against a real MySQL database.

```
Traceback (most recent call last):                                              
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)                                            
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)     
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)                                           
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)                              
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)                                       
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)                                          
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc                                                                   
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)                                
  File "/home/ubuntu/song_maker_gallery/django_smg/gallery/api.py", line 73, in get
    return Response(GalleryDatasetSerializer().render(slug=slug))               
  File "/home/ubuntu/song_maker_gallery/django_smg/gallery/serializers.py", line 117, in render
    for song in iter_fetch_and_cache(                                           
  File "/home/ubuntu/song_maker_gallery/django_smg/gallery/services.py", line 38, in iter_fetch_and_cache
    for song in songs:                                                          
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()                                                           
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))                       
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1143, in execute_sql
    sql, params = self.as_sql()                                                 
  File "/home/ubuntu/song_maker_gallery/django_smg/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 542, in as_sql
    raise TransactionManagementError('select_for_update cannot be used outside of a transaction.')
django.db.transaction.TransactionManagementError: select_for_update cannot be used outside of a transaction.
```

**Comment by jdevries3133** [comment]
According to Django docs:

> ["By default, select_for_update() locks all rows that are selected by the query."](https://docs.djangoproject.com/en/dev/ref/models/querysets/#select-for-update)

I tested and found this was indeed the case, and I was mistaken: there never was a race condition. Thanks Django!
