### ISSUE TITLE
Issues with setting up a dev environment

### ISSUE THREAD

**Issue by zeina99** [jdevries3133/song_maker_gallery#53]
I'm following the Development Setup steps and I'm facing some issues.

1.  I am not sure how or where to set the environment variable DJANGO_DEBUG. 
I would appreciate help on that.

2. Upon running `python manage.py migrate` I got some errors and here's the error log:
It seems to be trying to import some variables from `secret_settings.py` which dont exist since there were no instructions to set them up in `Contributing.md`. 

```
Traceback (most recent call last):
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/core/management/base.py", line 86, in wrapped
    saved_locale = translation.get_language()
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/utils/translation/__init__.py", line 254, in get_language
    return _trans.get_language()
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
    if settings.USE_I18N:
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/django_smg/settings.py", line 10, in <module>
    from .production_settings import *
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/django_smg/production_settings.py", line 9, in <module>
    from .secret_settings import (
ImportError: cannot import name 'EMAIL_HOST_USER' from 'django_smg.secret_settings' (/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/django_smg/secret_settings.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/manage.py", line 26, in <module>
    main()
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/django_smg/settings.py", line 10, in <module>
    from .production_settings import *
  File "/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/django_smg/production_settings.py", line 9, in <module>
    from .secret_settings import (
ImportError: cannot import name 'EMAIL_HOST_USER' from 'django_smg.secret_settings' (/Users/zeinathabet/Developer/opensource/song_maker_gallery/django_smg/django_smg/secret_settings.py)
```

**Note:**
I would also like to add that the dev bashscript adds some variables to `secret_settings.py` which are not mentioned in the written  instructions which are: 
```
MYSQL_PASSWORD = 'passwd'
MYSQL_USER = 'songmaker'
MYSQL_NAME = 'songmaker'
```
So I'm not sure if they are required or not

**Comment by zeina99** [comment]
Managed to fix the issue
